apiVersion: v1
kind: Service
metadata:
  name: {{ include "eru-brand.fullname" . }}
  labels:
    {{- include "eru-brand.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port }}"
    prometheus.io/path: "/api/v1/metrics"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "eru-brand.selectorLabels" . | nindent 4 }}
