apiVersion: v1
kind: Service
metadata:
  name: {{ include "brand.fullname" . }}
  labels:
    {{- include "brand.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
  selector:
    {{- include "brand.selectorLabels" . | nindent 4 }}
